import type { Metadata } from "next";
import { Geist, Geist_Mono, Nunito } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Background from "../components/Background";
import ServiceSection from "../components/ServiceSection";
import AboutSection from "../components/AboutUs";
import CourseCategory from "../components/CourseCategory";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const nunito = Nunito({
  subsets: ["latin", "vietnamese"], // Rất quan trọng để không bị lỗi font tiếng Việt
  weight: ["300", "400", "500", "600", "700"], // Chọn các độ đậm cần thiết
  variable: "--font-nunito", // Đặt tên biến CSS (hữu ích nếu dùng Tailwind)
  display: "swap", // Giúp hiển thị chữ ngay lập tức trước khi tải xong font
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <Header />
        <Background />
        <ServiceSection />
        <AboutSection />
        <CourseCategory />
        {children}
      </body>
    </html>
  );
}
